name: Build and push

on:
  push:
    branches: [ master ]
    paths:
      - Dockerfile
      - .github/workflows/build_and_push.yml
    tags:
      - '*'
  pull_request:
    branches: [ master ]
    paths:
      - Dockerfile
      - .github/workflows/build_and_push.yml
  schedule:
    - cron:  '23 2 */7 * *'
  workflow_dispatch:

jobs:
  docker:
    runs-on: ubuntu-latest
    steps:
      -
        name: Checkout
        uses: actions/checkout@v5
      -
        name: Docker meta
        id: meta
        uses: docker/metadata-action@v5
        with:
          images: aivus/motion-rpi
          tags: |
            type=ref,event=branch
            type=ref,event=tag
      -
        name: Set up QEMU
        uses: docker/setup-qemu-action@v3
      -
        name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
      -
        name: Login to DockerHub
        uses: docker/login-action@v3
        if: github.event_name != 'pull_request'
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      -
        name: Build and push
        id: docker_build
        uses: docker/build-push-action@v6
        with:
          context: .
          platforms: linux/arm/v7,linux/arm64
          push: ${{ github.event_name != 'pull_request' }}
          tags: ${{ steps.meta.outputs.tags }}
          cache-from: type=gha
          cache-to: type=gha,mode=max
